sonar.projectKey=***
sonar.projectName=VerVal Lab 3

# Exclude generated coverage reports and build artifacts from analysis
sonar.exclusions=**/bin/**,**/obj/**,coverage/**,.sonarqube/**
sonar.test.exclusions=**/bin/**,**/obj/**
